# Generated by Django 4.2.16 on 2024-10-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Рецепт-ингредиент', 'verbose_name_plural': 'Рецепты-ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipetag',
            options={'verbose_name': 'Рецепт-тег', 'verbose_name_plural': 'Рецепты-теги'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'Корзина покупок', 'verbose_name_plural': 'Корзина покупок'},
        ),
    ]
