# Generated by Django 4.2.16 on 2024-09-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_quantity_recipeingredient_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default=0, max_length=32, verbose_name='Цвет'),
            preserve_default=False,
        ),
    ]
