# Generated by Django 4.2.16 on 2024-10-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_link',
            field=models.URLField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
